version: '3'

services:
  app:
    image: node:18
    container_name: www
    restart: unless-stopped
    command: node index.js
    working_dir: /mount/repo/packages/pockethost.io/dist-server
    volumes:
      - ..:/mount/repo
    networks:
      - app-network
    ports:
      - '9000:3000'
    depends_on:
      - pbproxy
    env_file:
      - ./.env
  pbproxy:
    env_file:
      - ./.env
    image: node:18
    container_name: pbproxy
    restart: unless-stopped
    command: yarn serve
    working_dir: /mount/repo/packages/daemon/
    volumes:
      - ..:/mount/repo
      - ../packages/pocketbase/pocketbase:/mount/pocketbase/bin/pocketbase
      - ./mount/pocketbase/instances:/mount/pocketbase/instances
    networks:
      - app-network
    ports:
      - '9001:3000'
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - app
      - pbproxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./mount/logs:/mount/logs
      - ./mount/ssl:/mount/ssl
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
